services:
  - type: web
    name: moukogi3-web
    repo: https://github.com/mouko-mouyele/moukogi3
    branch: main
    env: static
    buildCommand: composer install --no-dev --optimize-autoloader
    startCommand: bash bin/start.sh
    envVars:
      - key: APP_ENV
        value: production
      - key: DB_CONNECTION
        value: mysql
